"""Updated NutritionalValue model to store concatenated nutrient values

Revision ID: 654087489ce5
Revises: c2da34d2a90d
Create Date: 2024-05-26 14:20:57.979037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654087489ce5'
down_revision = 'c2da34d2a90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Calories', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('TotalFat', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('SaturatedFat', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Cholesterol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Sodium', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('TotalCarbohydrates', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('DietaryFiber', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Sugars', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Protein', sa.String(length=50), nullable=True))
        batch_op.drop_column('sugars')
        batch_op.drop_column('calories')
        batch_op.drop_column('saturatedFat')
        batch_op.drop_column('totalCarbohydrates')
        batch_op.drop_column('protein')
        batch_op.drop_column('dietaryFiber')
        batch_op.drop_column('sodium')
        batch_op.drop_column('totalFat')
        batch_op.drop_column('cholesterol')

    with op.batch_alter_table('recipes_nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Calories', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('TotalFat', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('SaturatedFat', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Cholesterol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Sodium', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('TotalCarbohydrates', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('DietaryFiber', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Sugars', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Protein', sa.String(length=50), nullable=True))
        batch_op.drop_column('sugars')
        batch_op.drop_column('calories')
        batch_op.drop_column('saturatedFat')
        batch_op.drop_column('totalCarbohydrates')
        batch_op.drop_column('protein')
        batch_op.drop_column('dietaryFiber')
        batch_op.drop_column('sodium')
        batch_op.drop_column('totalFat')
        batch_op.drop_column('cholesterol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cholesterol', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalFat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dietaryFiber', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('protein', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalCarbohydrates', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saturatedFat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calories', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sugars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('Protein')
        batch_op.drop_column('Sugars')
        batch_op.drop_column('DietaryFiber')
        batch_op.drop_column('TotalCarbohydrates')
        batch_op.drop_column('Sodium')
        batch_op.drop_column('Cholesterol')
        batch_op.drop_column('SaturatedFat')
        batch_op.drop_column('TotalFat')
        batch_op.drop_column('Calories')

    with op.batch_alter_table('nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cholesterol', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalFat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dietaryFiber', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('protein', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalCarbohydrates', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saturatedFat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calories', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sugars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('Protein')
        batch_op.drop_column('Sugars')
        batch_op.drop_column('DietaryFiber')
        batch_op.drop_column('TotalCarbohydrates')
        batch_op.drop_column('Sodium')
        batch_op.drop_column('Cholesterol')
        batch_op.drop_column('SaturatedFat')
        batch_op.drop_column('TotalFat')
        batch_op.drop_column('Calories')

    # ### end Alembic commands ###
