"""Updated models

Revision ID: 75956cf3164b
Revises: 654087489ce5
Create Date: 2024-05-26 15:14:54.059085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75956cf3164b'
down_revision = '654087489ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutritional_values', schema=None) as batch_op:
        batch_op.alter_column('Calories',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('TotalFat',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('SaturatedFat',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('Cholesterol',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('Sodium',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('TotalCarbohydrates',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('DietaryFiber',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('Sugars',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('Protein',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)

    with op.batch_alter_table('recipes_nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('totalFat', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('saturatedFat', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('cholesterol', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('totalCarbohydrates', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('dietaryFiber', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('sugars', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.drop_column('DietaryFiber')
        batch_op.drop_column('Calories')
        batch_op.drop_column('Sodium')
        batch_op.drop_column('TotalFat')
        batch_op.drop_column('Sugars')
        batch_op.drop_column('Protein')
        batch_op.drop_column('SaturatedFat')
        batch_op.drop_column('TotalCarbohydrates')
        batch_op.drop_column('Cholesterol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_nutritional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cholesterol', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('TotalCarbohydrates', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('SaturatedFat', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Protein', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Sugars', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('TotalFat', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Sodium', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Calories', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DietaryFiber', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('protein')
        batch_op.drop_column('sugars')
        batch_op.drop_column('dietaryFiber')
        batch_op.drop_column('totalCarbohydrates')
        batch_op.drop_column('sodium')
        batch_op.drop_column('cholesterol')
        batch_op.drop_column('saturatedFat')
        batch_op.drop_column('totalFat')
        batch_op.drop_column('calories')

    with op.batch_alter_table('nutritional_values', schema=None) as batch_op:
        batch_op.alter_column('Protein',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Sugars',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('DietaryFiber',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('TotalCarbohydrates',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Sodium',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Cholesterol',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('SaturatedFat',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('TotalFat',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Calories',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
